# Uncomment the next line to define a global platform for your project
# platform :ios, '5.0'

target 'DEMO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'UIButton+Blocks','~>1.0.0'

  # Pods for DEMO

end
